### PR TITLE
Qbs fixes for osx

### PR DESCRIPTION
**Pull request by Daandelange**
I updated the QBS file to be more consistent:
- Use `of_root` instead of `../../../`
- ofxFft compilation fixes
- ofxDHT compilation fixes
- ofxSyphon missing file
- of_v0.12 update: `osx min SDK to 10.15` and `cpp c++17`

What IDE are you using on Linux atm ?

### CODE REVIEW

**Comment by d3cod3** [comment]
Thanks for the fixes Daan!

Can you please close this and re-make the same PR to [0.7.0-pre-release](https://github.com/d3cod3/Mosaic/tree/0.7.0-pre-release) branch? I'm working there for the next release to maintain some order ( finally )

On linux i'm still working with qtcreator 4.15.2, the same .qbs file, i'm happy with that.

**Comment by d3cod3** [comment]
I've already added your fixes, linux ok, later i'll test them on my macos machine

**Comment by Daandelange** [comment]
Ok, thanks !
Note that qbs support is gone since of_v0.12.0, it still works but it is to be considered depreciated and soon-to-be obsoleted.

Also, while I really love Qbs, I found some edge cases that revealed how compilation is not identical to XCode or makefile builds. For example addons are compiled with flags and includes from other addons, which can lead to very weird runtime behaviours, specially with objc-c files (ofxSyphon, ofxImGui, ofVideoGrabber, etc.) on mac; that have become more sensitive in of_v0.12.0 with ARC disabled.
Maybe this is the reason why they depreciated qbs ?

It looks like a bunch of OFers are currently looking into a "true" (common) build system (chalet, meson, cmake), I really hope this becomes something !

Also, on osx, I'm having very weird runtime crashes with Qt builds so Im using MakeFiles for building while editing in Qt-Creator. It might be a linker mistake (different lib for compiling and running), or something on my side, my of installation is not 100% fresh. I'd be curious how your osx-qbs build runs !

I tried editing with VSCodium but it's so damn slow, and building Mosaic on it makes my Mac crash maxing out my 32Gb of RAM, hanging like when you compile openFrameworks without changing the VRAM settings on rpi.

What's your IDE atm for debugging ? For releasing ?

**Comment by d3cod3** [comment]
Already tested changes on macOS, everything is fine!

About what you comment, yeah, i hope they switch to cmake or something similar soon, it would be a really good upgrade for OF.

I'm using qtcreator on both macOS and linux, this:

Captura de pantalla 2024-12-11 a las 14 36 41

on macOS Big Sur 11.4, and the 4.15.2 version on linux
so far, no problems on both territories, for now

Mainly i debug with the qtcreator debugger, on linux, because i prefer it, and because it's more stricter on warnings/errors ( generally ), but for the future i would like to learn to use Tracy properly. and debug stuff with that.

Mac release has been installed on more than 50 computers in a classroom, plus the personal students laptops, macOS mainly, with a small percentage of linux ( ubuntu, fedora, mint, debian that i've seen ), and everything run smoothly, different OS versions and all, mainly macOS 12, 13 and 14, and some 15 ( i've fixed some old problematic bugs with release 0.6.9 )

I'm happy with the results for now, plus the install from [flathub](https://flathub.org/apps/org.d3cod3.Mosaic) for linux run 99% without issues, the only object that crash it's the video grabber, it seems that camera access provoke a kernel error, i've not find a fix yet.

Anyway, i'm finishing the 0.7.0 release this week, next week have a Mosaic presentation, more fixes and new stuff, check the [TODO list](https://github.com/d3cod3/Mosaic/issues/80)

Let me know sometimes when you'll use it, and we'll talk in the Mosaic chatroom, it's vintage and old school ( text only ) but at least it has copy&paste :P

**Comment by Daandelange** [comment]
Thanks for these infos.
Awesome for the number of installs ! 🎉 

> Mainly i debug with the qtcreator debugger, on linux, because i prefer it, and because it's more stricter on warnings/errors ( generally ), but for the future i would like to learn to use Tracy properly. and debug stuff with that.

I see these as complimentary : Tracy is more a profiling utility while the gdb debugger (in Qt) is useful for detecting anormal behaviour / inspecting states.
On osx 10.15 I'm using Qt-Creator 4.15.2 too, should I downgrade that ? (or didn't you try it on osx?)

Ok, I'll try to catch you in Mosaic ;)

**Comment by d3cod3** [comment]
No, i don't think to be an issue the different Qt-Creator release, probably it's because i installed that version on my macOS machins long time ago and never upgraded it.

**Comment by d3cod3** [comment]
I'm closing this, let's talk soon!

**Pull request closed without merging**
